version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      DB_HOST: database
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: project2
    depends_on:
      - backend
    ports:
      - "50000:5000"
    networks:
      - project2net

  database:
    image: mariadb:latest
    container_name: project2_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project2
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      FLASK_APP: app.py
      FLASK_ENV: development
    ports:
      - "3306:3306"
    networks:
      - project2net
    volumes:
      - ./init:/docker-entrypoint-initdb.d
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: project2_backend
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: project2
      FLASK_APP: backend.py
      FLASK_ENV: development
    ports:
      - "5001:5001"
    networks:
      - project2net

networks:
  project2net:
    driver: bridge